name:                blockchain
version:             0.1.0.0
synopsis:            Simple project template from stack
description:         Please see README.md
homepage:            https://github.com/githubuser/blockchain#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
extra-source-files:
  - README.md

ghc-options: -Wall -Werror

default-extensions:
  - BangPatterns
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - byteable
  - bytestring
  - cryptonite
  - either
  - errors
  - hashable
  - memory
  - mtl
  - text
  - time
  - transformers
  - unordered-containers

library:
  source-dirs: lib
  exposed-modules:
    - Data.Blockchain.Core.Blockchain
    - Data.Blockchain.Core.Builder.Transaction
    - Data.Blockchain.Core.Crypto
    - Data.Blockchain.Core.Crypto.ECDSA
    - Data.Blockchain.Core.Crypto.Hash
    - Data.Blockchain.Core.Crypto.HashTree
    - Data.Blockchain.Core.Types
    - Data.Blockchain.Core.Types.Block
    - Data.Blockchain.Core.Types.Difficulty
    - Data.Blockchain.Core.Types.Transaction
    - Data.Blockchain.Mining.Block

executables:
  blockchain:
    main: Main.hs
    source-dirs: exec
    dependencies:
      - blockchain

tests:
  spec:
    main: Main.hs
    source-dirs:
      - test
    dependencies:
      - blockchain
      - hspec
      - QuickCheck
