name:                blockchain
version:             0.0.3
synopsis:            Generic blockchain implementation.
description:         Please see README.md
homepage:            https://github.com/TGOlson/blockchain
license:             BSD3
author:              Tyler Olson
maintainer:          tydotg@gmail.com
copyright:           2017 Tyler Olson
category:            Blockchain
extra-source-files:
  - README.md

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - DefaultSignatures
  - DeriveGeneric
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - byteable
  - bytestring
  - cryptonite
  - either
  - errors
  - hashable
  - memory
  - mtl
  - text
  - time
  - transformers
  - unordered-containers

library:
  source-dirs: lib
  exposed-modules:
    - Data.Blockchain
    - Data.Blockchain.Builder
    - Data.Blockchain.Crypto
    - Data.Blockchain.Types
    - Data.Blockchain.Mining

tests:
  spec:
    main: Main.hs
    source-dirs:
      - test
    dependencies:
      - async
      - blockchain
      - deepseq
      - hspec
      - QuickCheck
      - quickcheck-instances
