name:                blockchain-node
version:             0.0.1
synopsis:            Generic blockchain implementation.
description:         Please see README.md
homepage:            https://github.com/TGOlson/blockchain
license:             BSD3
author:              Tyler Olson
maintainer:          tydotg@gmail.com
copyright:           2017 Tyler Olson
category:            Blockchain
extra-source-files:
  - README.md

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - DataKinds
  - DefaultSignatures
  - DeriveGeneric
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeOperators

dependencies:
  - aeson
  - async
  - base >= 4.7 && < 5
  - blockchain-api
  - blockchain-core
  - bytestring
  - either
  - mtl
  - optparse-generic
  - servant-client
  - servant-server
  - stm
  - time
  - warp

executables:
  blockchain-node:
    main: Main.hs
    source-dirs: exec
    dependencies:
      - blockchain-node

library:
  source-dirs: lib
  exposed-modules:
    - Network.Blockchain.Node

tests:
  spec:
    main: Main.hs
    source-dirs:
      - test
    dependencies:
      - blockchain-node
      - hspec
      - QuickCheck
      - quickcheck-instances
